services:
  vymanager-backend:
    image: ghcr.io/community-vyprojects/vymanager-backend:main
    build:
      context: ..
      dockerfile: container/backend/Containerfile
    ports:
       - "3001:3001"
    volumes:
      # Sync time between container and host
      - /etc/localtime:/etc/localtime:ro
      # Mapping of the local .env file to the container, change ../backend/.env to the correct path
      - ../backend/.env:/app/.env:ro

  vymanager-frontend:
    image: ghcr.io/community-vyprojects/vymanager-frontend:main
    build:
      context: ..
      dockerfile: container/frontend/Containerfile
    ports:
      - "3000:3000"
    volumes:
      # Sync time between container and host
      - /etc/localtime:/etc/localtime:ro
      # Mapping of the local .env file to the container, change ../frontend/.env to the correct path
      - ../frontend/.env:/app/.env:ro
    depends_on:
      - vymanager-backend